---
title: "ANCOVA"
author: "Suraj Suresh Sajjan"
date: "December 13, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("effects");install.packages("compute.es");install.packages("multcomp"); install.packages("pastecs"); install.packages("WRS", repos="http://R-Forge.R-project.org"); install.packages("akima")

library(car); library(compute.es); library(effects); library(ggplot2);
library(multcomp); library(pastecs); library(WRS)


viagraData<-read.delim("D:/AMOD/AMOD-5240H-A-Statistical aspects of modeling/FInal term project/ViagraCovariate.dat", header = TRUE)

viagraData$dose<-factor(viagraData$dose, levels = c(1:3), labels = c("Placebo", "Low Dose", "High Dose"))


par(mfrow=c(1,2))
plot(x=viagraData$dose, y=viagraData$libido)
plot(x=viagraData$dose, y=viagraData$partnerLibido)

anova(lm(partnerLibido ~ dose, data = viagraData))



covariateFirst <- aov(libido ~ partnerLibido + dose, data = viagraData)
doseFirst <- aov(libido ~ dose + partnerLibido, data = viagraData)
summary(covariateFirst)
summary(doseFirst)


Anova(covariateFirst, type = "III")

contrasts(viagraData$dose)<-cbind(c(-2,1,1), c(0,-1,1))

viagraModel<-aov(libido ~ partnerLibido + dose, data = viagraData)
Anova (viagraModel, type= "III")


adjustedMeans<-effect("dose", viagraModel, se=TRUE)
summary(adjustedMeans)
adjustedMeans$se


#512/998
#455/988




#References:
# file - https://www.calvin.edu/~rpruim/data/grafen/leprosy.csv
#text book - Discovering Statistics using R by Andy Field



```